global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'elvara-sepsis-service'
    metrics_path: "/metrics"
    static_configs:
      # Railway internal DNS (private network)
      # Update this to "api:8000" for local Docker Compose testing
      - targets: ["fastapi.railway.internal:8000"]